#include <iostream>
using namespace std;
int main()
{
    char character ;
    cin>>character;
    switch (character)
    {
    case 'a':
        cout<<"VOWEL"<<endl;
        break;
    case 'e':
        cout<<"VOWEL"<<endl;
        break;
    case 'i':
        cout<<"VOWEL"<<endl;
        break;
    case 'o':
        cout<<"VOWEL"<<endl;
        break;
    case 'u':
        cout<<"VOWEL"<<endl;
        break;
    default:
        cout<<"CONSONENT"<<endl;
        break;
    }
    
    
    return 0;
}